version: 2.1

executors:
  go:
    docker:
      - image: circleci/golang:1.12
    working_directory: /tmp/octopus

jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    executor: go

    parallelism: 2

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v3-{{ checksum "go.sum" }}

      - run:
          name: Install linter
          command: |
            GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.16.0

      - run: make # pull and build dependencies for the project

      - run:
          name: List built binaries
          command: |
            pwd
            ls -l ./bin/

      - save_cache:
          key: go-mod-v3-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
          # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: bin
          # Must be relative path from root
          paths:
            - pushd
  deploy:
    executor: go
    steps:
      - add_ssh_keys:
          fingerprints:
            - "73:b6:96:34:a1:e8:b6:2e:b2:d1:6a:73:e0:ad:8b:3e"
      - attach_workspace:
          at: /tmp/octopus/bin
      - run:
          name: List built binaries
          command: |
            pwd
            ls -l ./bin/
      - run:
          name: Deploy over ssh
          command: |
            mkdir ~/.ssh
            ssh-keyscan $DEVNET_HOST >> ~/.ssh/known_hosts
            scp bin/pushd "$DEVNET_USER@$DEVNET_HOST:$DEPLOY_LOCATION/pushd"
            ssh $DEVNET_USER@$DEVNET_HOST "cd $SERVICE_LOCATION && docker-compose up --build -d pushd"
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
