[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "=v0.1.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "=v1.16.26"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "=v1.7.0"

[prune]
  go-tests = true
  unused-packages = true